site_name: Final Project Starter Pack HIS 4936
theme_dir: theme
theme: null
copyright: 'Copyright &copy; 2018 <a href="mailto:
repo_url: https://github.com/thePortus/his4936-starter
repo_name: 'GitHub'
pages:
- Home: 'index.md'
- Background: 'background.md'
- Source Analysis: 'source_analysis.md'
- Workflow: 'workflow.md'
- Initial Findings: 'initial_findings.md'
- Reflections: 'reflections.md'
- Bibliography and Credits: 'biblio_and_credits.md'
